#
# Script module for module 'AzureRM.CostManagement'
# Generated by: Kilian Arjona
#
# Generated on: 27/10/2017
#

# Get public and private function definition files
$PSModule = $ExecutionContext.SessionState.Module
$PSModuleRoot = $PSModule.ModuleBase

$Public  = @(Get-ChildItem -Path $PSModuleRoot\public\*.ps1 -ErrorAction SilentlyContinue)
$Private = @(Get-ChildItem -Path $PSModuleRoot\private\*.ps1 -ErrorAction SilentlyContinue)

# Dot source the files
foreach($import in @($Public + $Private)) {
    try {
        . $import.fullname
    } catch {
        Write-Error -Message "Failed to import function $($import.fullname): $_"
    }
}

# Make the cmdlets available
Export-ModuleMember -Function $Public.Basename